//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSReader.Properties
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSSReader.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to E_xit.
		/// </summary>
		public static string ExitMenuItem
		{
			get
			{
				return ResourceManager.GetString("ExitMenuItem", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to F_eeds.
		/// </summary>
		public static string FeedsMenuName
		{
			get
			{
				return ResourceManager.GetString("FeedsMenuName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to _File.
		/// </summary>
		public static string FileMenuName
		{
			get
			{
				return ResourceManager.GetString("FileMenuName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No items to display.
		/// </summary>
		public static string MainWindow_NoItems
		{
			get
			{
				return ResourceManager.GetString("MainWindow_NoItems", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to RSS Reader.
		/// </summary>
		public static string MainWindowTitle
		{
			get
			{
				return ResourceManager.GetString("MainWindowTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enable HTML formatting.
		/// </summary>
		public static string Settings_EnableFormattingLabelContent
		{
			get
			{
				return ResourceManager.GetString("Settings_EnableFormattingLabelContent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Error.
		/// </summary>
		public static string Settings_Error
		{
			get
			{
				return ResourceManager.GetString("Settings_Error", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid update interval.
		/// </summary>
		public static string Settings_InvalidUpdateInterval
		{
			get
			{
				return ResourceManager.GetString("Settings_InvalidUpdateInterval", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid URL: {0}.
		/// </summary>
		public static string Settings_InvalidUri
		{
			get
			{
				return ResourceManager.GetString("Settings_InvalidUri", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ok.
		/// </summary>
		public static string Settings_Ok
		{
			get
			{
				return ResourceManager.GetString("Settings_Ok", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Feeds sources: (One per line).
		/// </summary>
		public static string Settings_SourcesLabelContent
		{
			get
			{
				return ResourceManager.GetString("Settings_SourcesLabelContent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update interval:.
		/// </summary>
		public static string Settings_UpdateIntervalLabelContent
		{
			get
			{
				return ResourceManager.GetString("Settings_UpdateIntervalLabelContent", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to _Settings.
		/// </summary>
		public static string SettingsMenuItem
		{
			get
			{
				return ResourceManager.GetString("SettingsMenuItem", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Settings.
		/// </summary>
		public static string SettingsWindowTitle
		{
			get
			{
				return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
			}
		}
	}
}
